@startuml
left to right direction

actor Cliente
actor "Entregador Jet" as Entregador
actor Sistema
actor Admin

package "App JetEntregas" {
    usecase "Cadastrar-se" as UC01
    usecase "Fazer login" as UC02
    usecase "Cadastrar CPF e endereço" as UC03
    usecase "Receber notificação de pedido" as UC04
    usecase "Visualizar status do pedido" as UC05
    usecase "Visualizar histórico de entregas" as UC06
}

package "Entrega Jet" {
    usecase "Visualizar pedidos no locker" as UC08
    usecase "Confirmar retirada do locker" as UC09
    usecase "Marcar como entregue" as UC10
}

package "Sistema" {
    usecase "Vincular pedido via CPF + Endereço" as UC11
    usecase "Notificar cliente" as UC13
    usecase "Registrar logs de entrega" as UC14
    usecase "Integrar com APIs de marketplaces" as UC12
}

package "Administração" {
    usecase "Gerenciar entregadores" as UC15
    usecase "Visualizar relatórios" as UC16
}

Cliente --> UC01
Cliente --> UC02
Cliente --> UC03
Cliente --> UC04
Cliente --> UC05
Cliente --> UC06

Entregador --> UC02
Entregador --> UC08
Entregador --> UC09
Entregador --> UC10

UC04 <-- UC13
UC05 <-- UC11
UC08 <-- UC11
UC03 --> UC11 : <<include>>
UC11 --> UC12 : <<extend>>

UC09 --> UC14 : <<include>>
UC10 --> UC14 : <<include>>

Admin --> UC15
Admin --> UC16

@enduml
