@startuml

class Usuario {
  nome: String
  cpf: String
  email: String
  senha: String
  realizarLogin(email: String, senha: String): boolean
  alterarSenha(senhaAtual: String, novaSenha: String): void
}

class Cliente {
  endereco: String
  telefone: String
  visualizarPedidos(): List<Pedido>
  realizarPagamento(pedido: Pedido): void
}

class EntregadorJet {
  matricula: String
  possuiCarteiraJetski: Boolean
  retirarDoLocker(p: Pedido): void
  marcarComoEntregue(p: Pedido): void
}

class Pedido {
  id: String
  status: String
  dataRecebimento: Date
  dataEntrega: Date
  notificarCliente(): void
}

class Locker {
  id: String
  localizacao: String
  armazenarPedido(p: Pedido): void
}

class Notificacao {
  id: String
  mensagem: String
  dataHora: Date
}

class ServicoDeNotificacao {
  enviarNotificacao(mensagem: String, destino: Cliente): void
}

class Pagamento {
  id: String
  valor: Float
  status: String
  metodo: String
  processarPagamento(): boolean
}


Usuario <|-- Cliente
Usuario <|-- EntregadorJet

Cliente  -->  Pedido
Cliente  -->  Notificacao
Pedido  -->  Locker
Pedido  -->  EntregadorJet
Pedido  -->  Notificacao
Pedido  -->  Pagamento
Pedido --> ServicoDeNotificacao

@enduml
